### ISSUE TITLE
Where is the BlockController.cs Script?

### ISSUE THREAD

**Issue by MacJuicer** [angelotadres/RunAndJump#1]
In page 94 of "Extending Unity with Editor Scripting" book appears a table with this

SolidDirt          Blocks       Dirt         BlockController.cs
SolidGrass      Blocks       Grass     BlockController.cs

But I didn't found the BlockController.cs script in the tree project.

**Comment by angelotadres** [comment]
Hi.

Sorry about that and the delay of my answer.
I added the script to the project. Just FYI you can use LevelPiece instead (BlockController is just an empty wrapper)

Thanks.
